kind: Service
apiVersion: v1
metadata:
  name: helidon-rest
  labels:
    app: helidon-rest
spec:
  type: NodePort
  selector:
    app: helidon-rest
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helidon-rest
  template:
    metadata:
      labels:
        app: helidon-rest
        version: v1
    spec:
      containers:
      - name: helidon-rest
        image: helidon-rest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
